# .github/workflows/docker-image.yml
# Made by Abhishek Bhatia
# GitHub Actions workflow to build and run the Docker image for the Discord bot.

name: Build and Deploy Discord Bot

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/discord-bot:latest

    - name: Run Docker container
      run: |
        docker run -d --name discord-bot -e DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} ${{ secrets.DOCKER_USERNAME }}/discord-bot:latest
